language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t masato/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true masato/docker-react npm run test -- --coverage --watchAll=false

